### ISSUE TITLE
Raspbian: [getAPIKeys] Error RequestError EPROTO

### ISSUE THREAD

**Issue by lockpicker** [lockpicker/homebridge-honeywell-tuxedo-touch#1]
When loading the plugin on Hoobs or raspbian based system, the following error is encountered: 

[8/31/2020, 23:41:21] Homebridge is running on port 51983.
(node:8428) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
[8/31/2020, 23:41:21] [Home Security] [getAPIKeys] Error: RequestError: Error: write EPROTO 3069934032:error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small:../deps/openssl/openssl/ssl/statem/statem_clnt.c:2150:

    at new RequestError (/usr/local/lib/node_modules/homebridge-honeywell-tuxedo-touch/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/usr/local/lib/node_modules/homebridge-honeywell-tuxedo-touch/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/homebridge-honeywell-tuxedo-touch/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/usr/local/lib/node_modules/homebridge-honeywell-tuxedo-touch/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.onRequestError (/usr/local/lib/node_modules/homebridge-honeywell-tuxedo-touch/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:315:20)
    at errorOrDestroy (internal/streams/destroy.js:108:12)
    at onwriteError (_stream_writable.js:424:5)
    at onwrite (_stream_writable.js:445:5)
    at internal/streams/destroy.js:50:7
    at TLSSocket.Socket._destroy (net.js:679:5)
    at TLSSocket.destroy (internal/streams/destroy.js:38:8)
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:93:12) {
  cause: Error: write EPROTO 3069934032:error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small:../deps/openssl/openssl/ssl/statem/statem_clnt.c:2150:
  
      at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:92:16) {
    errno: 'EPROTO',
    code: 'EPROTO',
    syscall: 'write'
  },
  error: Error: write EPROTO 3069934032:error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small:../deps/openssl/openssl/ssl/statem/statem_clnt.c:2150:
  
      at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:92:16) {
    errno: 'EPROTO',
    code: 'EPROTO',
    syscall: 'write'
  },
  options: {
    jar: true,
    url: 'https://lockpicker.synology.me/tuxedoapi.html',
    headers: { 'User-Agent': 'homebridge' },
    callback: [Function: RP$callback],
    transform: undefined,
    simple: true,
    resolveWithFullResponse: false,
    transform2xxOnly: false
  },
  response: undefined
}

**Comment by lockpicker** [comment]
This issue is documented here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=907788

Newer versions of Debian have moved the openssl config to be stricter by default, and unfortunately the Honeywell tuxedo unit comes bundled with an old ssl cert which causes all sorts of issues with SSL/TLS getting stricter.

The only fix I've found for this so far is one of the following: 

If you are running this on a raspberry pi, ssh into the pi unit: 
In the /etc/ssl/openssl.cnf

1. Change 
CipherString = DEFAULT@SECLEVEL=2   to 
CipherString = DEFAULT@SECLEVEL=1 

A simple way to achieve this is: 
``` 
1. ssh pi@<YOUR_RASPBERRY_PI_IP_ADDRESS>
2. sudo sed -i 's/CipherString = DEFAULT@SECLEVEL=2/CipherString = DEFAULT@SECLEVEL=1/g' /etc/ssl/openssl.cnf
```

2. Remove the CipherString = DEFAULT@SECLEVEL=2 line all together

Whilst not ideal, either of these should be acceptable for the homebridge setup.
