### ISSUE TITLE
Got SIGTERM - Crashing Homebridge

### ISSUE THREAD

**Issue by woppermann** [lockpicker/homebridge-honeywell-tuxedo-touch#9]
HOMEBRIDGE V1.2.3
homebridge-honeywell-tuxedo-touch v1.4.4

(node:10432) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.
[11/3/2020, 8:59:01 AM] TypeError: Cannot read property 'sigBytes' of undefined
    at new init (/usr/lib/node_modules/homebridge-honeywell-tuxedo-touch/node_modules/crypto-js/hmac.js:53:22)
    at Object.HmacSHA1 (/usr/lib/node_modules/homebridge-honeywell-tuxedo-touch/node_modules/crypto-js/core.js:781:25)
    at HoneywellTuxedoAccessory.getAlarmMode (/usr/lib/node_modules/homebridge-honeywell-tuxedo-touch/index.js:397:14)
    at HoneywellTuxedoAccessory.handleSecuritySystemCurrentStateGet (/usr/lib/node_modules/homebridge-honeywell-tuxedo-touch/index.js:195:18)
    at SecuritySystemCurrentState.emit (events.js:315:20)
    at SecuritySystemCurrentState.EventEmitter.emit (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at SecuritySystemCurrentState.Characteristic._this.getValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:489:12)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1239:22
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._this._handleGetCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1167:10)
[11/3/2020, 8:59:01 AM] Got SIGTERM, shutting down Homebridge...
[11/3/2020, 8:59:06 AM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[11/3/2020, 8:59:11 AM] [HB Supervisor] Restarting Homebridge...
[11/3/2020, 8:59:11 AM] [HB Supervisor] Starting Homebridge with extra flags: -I
[11/3/2020, 8:59:11 AM] [HB Supervisor] Started Homebridge v1.2.3 with PID: 10466
[11/3/2020, 8:59:12 AM] Loaded config.json with 1 accessories and 3 platforms.
[11/3/2020, 8:59:12 AM] ---
[11/3/2020, 8:59:13 AM] Loaded plugin: homebridge-config-ui-x@4.31.0
[11/3/2020, 8:59:13 AM] Registering platform 'homebridge-config-ui-x.config'
[11/3/2020, 8:59:13 AM] ---
[11/3/2020, 8:59:13 AM] Loaded plugin: homebridge-honeywell-tuxedo-touch@1.4.4
[11/3/2020, 8:59:13 AM] Registering accessory 'homebridge-honeywell-tuxedo-touch.Honeywell Tuxedo Touch'
[11/3/2020, 8:59:13 AM] ---
[11/3/2020, 8:59:13 AM] Loaded plugin: homebridge-myq@2.3.3
[11/3/2020, 8:59:13 AM] Registering platform 'homebridge-myq.myQ'
[11/3/2020, 8:59:13 AM] ---

**Comment by lockpicker** [comment]
Could you please send through the relevant section of your config.json. This looks like homebridge can't reach the tuxedo unit over ip.
